services:
  backend:
    env_file: backend/.env
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    networks:
      - net-tier

networks:
  net-tier:
    driver: bridge
