# Generated by Django 5.1.7 on 2025-04-28 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendr', '0002_category_genre_language_mediaage_mediatype_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='recommendr.mediatype'),
        ),
        migrations.AddField(
            model_name='genre',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='recommendr.mediatype'),
        ),
    ]
